### ISSUE TITLE
get rid of itertools

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/AnalysisToolbox#11]
Many systems seem not to be able to download it somehow, and it is more for convenience than actually necessary.

**Comment by luhuhis** [comment]
Isn't itertools part of the default python packages and so it's not necessary to have it in requirements? (I.e. that's why it can be installed, because it's already there?)
Itertools is really useful, replacing it would be very cumbersome

**Comment by clarkedavida** [comment]
You are right, I'm removing it from requirements.txt now and closing the issue...

I'm not sure what led me to think it is an outside package.
